ecommerce/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'),)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/ecommerce/store/urls.py
from django.urls import path, include


from . import views

urlpatterns = [
        #Leave as empty string for base url
	path('', views.store, name="store"),
	path('rentals/', views.rental_store, name="rental_store"),
	path('sales/', views.sale_store, name="sale_store"),
	path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),
	path('property/<int:id>', views.property_type, name="property_type"),
	path('update_item/', views.updateItem, name="update_item"),
	path('process_order/', views.processOrder, name="process_order"),
	path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),
	path('logout/', views.logoutUser, name="logout"),
	path('search/', views.search, name="search"),
	path('x/', views.store, name="Location_insert"),
	path('request/', views.req, name="request"),
	path('req_saved/', views.req, name="req_saved"),
]

ecommerce/ecommerce/store/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Mode(models.Model):
    modes = models.CharField(max_length=20)

    def __str__(self):
        return self.modes

class product_spec(models.Model):
    specs = models.CharField(max_length=20)

    def __str__(self):
        return self.specs

class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)
    # password 

    def __str__(self):
        return self.name

class Requests(models.Model):
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    request = models.CharField(max_length=500)
    # password 

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=40)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=True)
    bedrooms = models.IntegerField(max_length=10, blank=True, null=True) 
    bathrooms = models.IntegerField(max_length=10, blank=True, null=True) 
    toilets =  models.IntegerField(max_length=10, blank=True, null=True) 
    location = models.CharField(max_length=200)
    description = models.IntegerField(max_length=10, blank=True, null=True)
    mode = models.ForeignKey(Mode, on_delete=models.CASCADE, blank=True, null=True)
    spec = models.ForeignKey(product_spec, on_delete=models.CASCADE, blank=True, null=True)
    featured = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name
    
    @property
    def imageURL(self):
        try:
            url = self.featured.url
        except:
            url = ""
        return url

class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ""
        print('URL: ', url)
        return url

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        # j=0
        for i in orderitems:
            if (i.product.digital == False) or (i.product.digital == "false"):
                shipping = True
            # j+=1
        return shipping

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __sstr__(self):
        return self.address


ecommerce/ecommerce/store/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# from chosen import forms as chosenforms
from django_select2 import forms as s2forms
from .models import Order, Requests
from datetime import date

class req_Form(ModelForm):
    class Meta:
        model = Requests
        fields = '__all__'

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email','password1','password2']

ecommerce/ecommerce/store/views.py
from django.shortcuts import render, redirect
from .models import *
from django.forms import inlineformset_factory
from django.http import JsonResponse
import json
import datetime
from . utils import cookieCart, cartData, guestOrder
from django.views.decorators.csrf import csrf_exempt
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm, req_Form
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            b = Customer(user=user, name=username, email=email)
            b.save()
            messages.success(request, "Account was created for " + username)
            return redirect('login')
    context = {'form': form}
    return render(request, 'store/register.html', context)
    
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username') 
        password = request.POST.get('password') 
        user = authenticate(request, username=username, password=password)
        print(user)
        print(username)
        if user is not None:
            login(request, user)
            return redirect('store')
        else:
            messages.info(request, 'Username OR password is incorrect')
    context = {}
    return render(request, 'store/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('login')

def store(request):
    if 'term' in request.GET:
        queryset = Product.objects.filter(location__icontains=request.GET.get('term')).distinct()
        results = list()
        for r in queryset:
            results.append(r.location)
        return JsonResponse(results, safe=False)
    elif 'spec' in request.GET:
        errors = []
        data = cartData(request)
        cartItems = data['cartItems']
        results = None
        context = {'products':results, 'cartItems': cartItems}
        if 'spec' in request.GET:
            # spec = request.GET['spec']
            # mode = request.GET['mode']
            location = request.GET['location']
            bedrooms = request.GET['bedroom']
            print(bedrooms, location)
            if not ((location or bedrooms) or location):
                print("errors")
                errors.append('Enter a search term.')
            else:
                results = Product.objects.filter(bedrooms__icontains=str(bedrooms)
                ).filter(
                    location__icontains=str(location)
                )
                # query = "spec: %s, mode: %s, location: %s" % (spec, mode, location)
                query = "bedrooms: %s, location: %s" % (bedrooms, location)
                print(len(results))
                context = {'products':results, 'cartItems': cartItems, 'query': query}
                return render(request, 'store/search.html', context)
        print("results")
        context = {'products':results, 'cartItems': cartItems, 'query': query}
        return render(request, 'store/search.html', context)
    data = cartData(request)
    cartItems = data['cartItems']
    Products = Product.objects.all()
    context = {'products':Products, 'cartItems': cartItems}
    return render(request, 'store/store.html', context)

def rental_store(request):
    data = cartData(request)
    cartItems = data['cartItems']
    Products = Product.objects.filter(mode="1")
    context = {'products':Products, 'cartItems': cartItems}
    return render(request, 'store/store.html', context)

def sale_store(request):
    data = cartData(request)
    cartItems = data['cartItems']
    Products = Product.objects.filter(mode="2")
    context = {'products':Products, 'cartItems': cartItems}
    return render(request, 'store/store.html', context)

def property_type(request, id=0):
    prop = Product.objects.get(pk=id)
    data = cartData(request)
    cartItems = data['cartItems']
    print(prop)
    context = {'product':prop, 'cartItems': cartItems}
    return render(request, 'store/property.html', context)

def cart(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        cookieData = cookieCart(request)
        cartItems = cookieData['cartItems']
        order = cookieData['order']
        print(order)
        items = cookieData['items']
        
    context = {'items':items, 'order':order,'cartItems': cartItems}
    # print(order.get_cart_total)
    return render(request, 'store/cart.html', context)



@csrf_exempt
def checkout(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    Products = Product.objects.all()
    context = {'products':Products, 'cartItems': cartItems}
        
    context = {'items':items, 'order':order, 'cartItems': cartItems}
    return render(request, 'store/checkout.html', context)

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('Product:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity +1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity -1)
    orderItem.save()
    if orderItem.quantity <=0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)
@csrf_exempt
def processOrder(request):
    transaction_id  = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        total = float(data['form']['total'])
        order.transaction_id = transaction_id
        if total == order.get_cart_total:
            order.complete = True
        order.save()
    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id
    if total == order.get_cart_total:
        order.complete = True
    order.save()
    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address = data['shipping']['address'],
            city = data['shipping']['city'],
            state = data['shipping']['state'],
            zipcode = data['shipping']['zipcode'],
            )

    return JsonResponse('Payment submitted..', safe=False)

def search(request):
    errors = []
    data = cartData(request)
    cartItems = data['cartItems']
    results = None
    context = {'products':results, 'cartItems': cartItems}
    print("xyz")
    if 'spec' in request.GET:
        spec = request.GET['spec']
        mode = request.GET['mode']
        location = request.GET['location']
        bedrooms = request.GET['bedrooms']
        if not ((spec or mode) or location):
            print("errors")
            errors.append('Enter a search term.')
        else:
            results = Product.objects.filter(
                spec__icontains=spec
            ).filter(
                mode__icontains=mode
            ).filter(
                location__icontains=location
            )
            query = "spec: %s, mode: %s, location: %s" % (spec, mode, location)
            print(results)
            context = {'products':results, 'cartItems': cartItems, 'query': query}
            return render(request, 'store/search.html', context)
    print("results")
    context = {'products':results, 'cartItems': cartItems, 'query': query}
    return render(request, 'store/search.html', context)

def req(request, id=0):
    data = cartData(request)
    cartItems = data['cartItems']
    form = req_Form()
    context = {'form': form, 'cartItems': cartItems,}
    if request.method == "GET":
        if id == 0:
            context = {'form': form,'cartItems': cartItems}
        else:
            itt = Requests.objects.get(pk=id)
            form = req_Form(instance=itt)
            context = {'form': form,'cartItems': cartItems,}
    if request.method == "POST":
        if id == 0:
            form = req_Form(request.POST)
        else:
            job = Requests.objects.get(pk=id)
            form = req_Form(request.POST,instance=job)
        if form.is_valid():
            form.save()
            # form.save_m2m()
        return render(request, "store/req_saved.html", context)
    return render(request, "store/req_form.html", context)

ecommerce/ecommerce/store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
{% load humanize %}
<div class="row">
	<div class="col-lg-12">
    <div class="box-element">
      <a class="btn btn-outline-dark" href="{% url 'store' %}">
        &#x2190; Continue Shopping
      </a>
      <br>
      <br>

      <table class="table">
        <tr>
          <th>
            <h5>Items: <strong>{{order.get_cart_items}}</strong></h5>
          </th>
          <th>
            <h6>Total: <strong>N{{order.get_cart_total|intcomma}}</strong></h6>
          </th>
          <th>
            <a style="float:right; margin:5px" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
          </th>
        </tr>
      </table>
    </div>
    <br>
   
<div class="box-element">
	<div class="cart-row">

    <div style="flex:2"><strong>Item</strong></div>
    <div style="flex:2"><strong>Name</strong></div>
		<div style="flex:1"><strong>Price</strong></div>
		<div style="flex:1"><strong>Quantity</strong></div>
		<div style="flex:1"><strong>Total</strong></div>
	</div>
	{% for item in items %}
	<div class="cart-row">
		<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
		<div style="flex:2"><p>{{item.product.name}}</p></div>
		<div style="flex:1"><p>{{item.product.price|floatformat:2}}</p></div>
		<div style="flex:1">
			<p class="quantity">{{item.quantity}}</p>
			<div class="quantity">
				<img data-id={{item.product.id}} data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">
		
				<img data-id={{item.product.id}} data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
			</div>
		</div>
		<div style="flex:1"><p>N{{item.get_total |intcomma}}</p></div>
  </div>
  {% endfor %}
  </div>
</div>
</div>

<script type="text/javascript">
  
  document.getElementById('section-div').innerHTML = ""
</script>
{% endblock content %}

ecommerce/ecommerce/store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
{% load humanize %}
<div class="row">
	<div class="col-lg-6">
		<div class="box-element" id="form-wrapper">
      <form id="form">
        <div id="user-info">
          <div class="form-field">
            <input required class="form-control" type="text" name="name" placeholder="Name..">
          </div>
          <div class="form-field">
            <input required class="form-control" type="email" name="email" placeholder="Email..">
          </div>
        </div>
        
        <div id="shipping-info">
          <hr>
          <p>Shipping Information:</p>
          <hr>
          <div class="form-field">
            <input class="form-control" type="text" name="address" placeholder="Address..">
          </div>
          <div class="form-field">
            <input class="form-control" type="text" name="city" placeholder="City..">
          </div>
          <div class="form-field">
            <input class="form-control" type="text" name="state" placeholder="State..">
          </div>
          <div class="form-field">
            <input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
          </div>
        </div>
        <hr>
        <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
      </form>
		</div>

      <br>
      <div class="box-element hidden" id="payment-info">
        <div id="paypal-button-container"></div>
      </div>
    </div>  
	<div class="col-lg-6">
		<div class="box-element">
      <a  class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; Back to Cart</a>
      <hr>
      <h3>Order Summary</h3>
      <hr>
      {% for item in items %}
          <div class="cart-row">
            <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
            <div style="flex:2"><p>{{item.product.name}}</p></div>
            <div style="flex:1"><p>N{{item.product.price |intcomma}}</p></div>
            <div style="flex:1"><p>x{{item.quantity}}</p></div>
          </div>
      {% endfor %}
      <h5>Items:   {{order.get_cart_items}}</h5>
      <h5>Total:   N{{order.get_cart_total|intcomma}}</h5>
    </div>
		</div>
  </div>
  
<script type="text/javascript">
    document.getElementById('section-div').innerHTML = ""
    var shipping = '{{order.shipping}}'
    var total = '{{order.get_cart_total}}'
    // console.log(user)
    if(shipping == 'False'){
      document.getElementById('shipping-info').innerHTML = ""
      
    }

    // if (user != 'AnonymusUser'){
    //   document.getElementById('user-info').innerHTML = ""
    //   console.log("user is not anonymus")
    // }

    if (shipping == 'False' && user != 'AnonymusUser'){
      document.getElementById('form-wrapper').classList.add("hidden");
      document.getElementById('payment-info').classList.remove("hidden");
    }

    var form = document.getElementById('form')
    form.addEventListener('submit', function(e){
      e.preventDefault()
      console.log('Form submitted...')
      document.getElementById('form-button').classList.add("hidden");
      document.getElementById('payment-info').classList.remove("hidden");
    })

    document.getElementById('make-payment').addEventListener('click', function(e){
      submitFormData()
    })
    function submitFormData(){
      console.log("Payment Button Clicked")
      var userFormData = {
        'name': null,
        'email': null,
        'total': total,
      }
      var shippingInfo = {
        'address': null,
        'city': null,
        'state': null,
        'zipcode': null,
      }

      if(shipping != 'False'){
        shippingInfo.address = form.address.value
        shippingInfo.city = form.city.value
        shippingInfo.state = form.state.value
        shippingInfo.zipcode = form.zipcode.value
      }
      if(user == 'AnonymousUser'){
        userFormData.name = form.name.value
        userFormData.email = form.email.value
      }
      var url = '/process_order/'
      fetch(url, {
        method: 'POST',
        headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken':csrftoken,
            },
            body:JSON.stringify({'form': userFormData, 'shipping':shippingInfo})
      })
      .then((response) => response.json())
      .then((data)=> {
          console.log('Success:', data);
          alert('Transaction completed');
          cart = {}
          document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
          window.location.href = "{% url 'store' %}"
      })
    }
</script>

<script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>
<script>
  // Render the PayPal button into #paypal-button-container
  paypal.Buttons({

      // Set up the transaction
      createOrder: function(data, actions) {
          return actions.order.create({
              purchase_units: [{
                  amount: {
                      value: '0.01'
                  }
              }]
          });
      },

      // Finalize the transaction
      onApprove: function(data, actions) {
          return actions.order.capture().then(function(details) {
              // Show a success message to the buyer
              alert('Transaction completed by ' + details.payer.name.given_name + '!');
          });
      }


  }).render('#paypal-button-container');
</script>
{% endblock content %}

ecommerce/ecommerce/store/templates/store/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
                    
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
                            <input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
                            <input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
                {% for message in messages %}
                    <p id="messages">{{message}}</p>
                {% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

ecommerce/ecommerce/store/templates/store/property.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
{% load humanize %}

<div class="row">
    <div class="col-lg-6">
        <div class="box-element">
			<div>

			<img id=featured src="{{product.imageURL}}">
			<div class="top-right"><span class="badge badge-secondary" style="margin-right: 5px;">{{product.mode}}</span></div>
		</div>
			<div id="slide-wrapper" >
				<img id="slideLeft" class="arrow" src="{% static 'images/arrow-left.png' %}">

				<div id="slider">
                    {% for image in product.image_set.all %}
                        <img class="thumbnail2" src="   
                        {{image.imageURL}}">
                    {% endfor%}
				</div>

				<img id="slideRight" class="arrow" src="{% static 'images/arrow-right.png' %}">
			</div>
        </div>
    </div>

		<div class="col-lg-6">
            <div class="box-element">
			<h1>{{product.name}} ({{product.spec}})</h1>
            <hr>
            <h4>BEDROOMS <span class="badge badge-secondary">{{product.bedrooms}}</span></h4>
            <h4>BATHROOMS <span class="badge badge-secondary">{{product.bathrooms}}</span></h4>
            <h4>TOILETS <span class="badge badge-secondary">{{product.toilets}}</span></h4>

			<h3>PRICE NGN {{product.price |intcomma}}</h3>

			<p>location {{product.location}} </p>
            <button data-action="add" data-id="{{product.id}}" class="btn btn-outline-secondary add-btn update-cart" >Add to Cart</button>
            <a class="btn btn-outline-success" href="{% url 'store' %}">BACK TO HOME</a>
		    </div>
        </div>
</div>

    <script type="text/javascript">
  
        document.getElementById('section-div').innerHTML = ""
         
		let thumbnails = document.getElementsByClassName('thumbnail2')

		let activeImages = document.getElementsByClassName('active2')

		for (var i=0; i < thumbnails.length; i++){

			thumbnails[i].addEventListener('mouseover', function(){
				console.log(activeImages)
				
				if (activeImages.length > 0){
					activeImages[0].classList.remove('active')
				}
				

				this.classList.add('active')
				document.getElementById('featured').src = this.src
			})
		}


		let buttonRight = document.getElementById('slideRight');
		let buttonLeft = document.getElementById('slideLeft');

		buttonLeft.addEventListener('click', function(){
			document.getElementById('slider').scrollLeft -= 180
		})

		buttonRight.addEventListener('click', function(){
			document.getElementById('slider').scrollLeft += 180
		})


	</script>

{% endblock content %}

ecommerce/ecommerce/store/templates/store/req_form.html
{% extends "store/main.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Requests</h1>
    <p class="lead font-italic">Kindly complete the form below to log a request with Property Sales</p>
    <hr class="my-4">

<form action="" method="post" autocomplete="off">
    {% csrf_token %}
    <div class="row" style="padding-bottom:5px">
        <div class="col-md-4">
            {{ form.name |as_crispy_field}}
        </div>
        
        <div class="col-md-4">
            {{ form.email |as_crispy_field }}
        </div>

        <div class="col-md-4">
            {{ form.phone |as_crispy_field}}
        </div>

    </div>
    <div class="row" style="padding-bottom: 20px;">
        <div class="col-md-12">
            {{ form.request|as_crispy_field }}
        </div>

    </div>
   
    <div class="row">
        <div class="col-md-8">
            <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-database"></i>
                Submit</button>
        </div>
                            
        <div class="col-md-4">
            <a href="{% url 'store' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-stream"></i> Properties
            </a>
        </div>
    </div>

</form>

</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js" integrity="sha512-rmZcZsyhe0/MAjquhTgiUcb4d9knaFc7b5xAfju483gbEXTkeJRUMIPk6s3ySZMYUHEcjKbjLjyddGWMrNEvZg==" crossorigin="anonymous"></script>
<script type="text/javascript">
    document.getElementById('section-div').innerHTML = ""
</script>
{% endblock content %}